### ISSUE TITLE
cuda memory error for periods > 1s

### ISSUE THREAD

**Issue by mguski** [UAF-SuperDARN-OPS/SuperDARN_UHD_Server#1]
running uafscan without --onesec results in this memory error

> cudamsg_handler: DEBUG    enter cuda_process_handler (swing 1)
> cuda_gpu    : DEBUG    nSamples_rx: bb=22356, if=1676775, rf=33535520
> Traceback (most recent call last):
>   File "./cuda_driver.py", line 1078, in <module>
>     main()
>   File "./cuda_driver.py", line 1069, in main
>     handler.process()
>   File "./cuda_driver.py", line 384, in process
>     self.gpu.rx_init(swing, cmd.payload['nSamples'])
>   File "./cuda_driver.py", line 673, in rx_init
>     self.rx_rf_samples = cuda.pagelocked_empty((self.nAntennas,  self.rx_rf_nSamples*2), np.int16, mem_flags=cuda.host_alloc_flags.DEVICEMAP)
> pycuda._driver.MemoryError: cuMemHostAlloc failed: out of memory

**Comment by mguski** [comment]
`uafscan --stid mcm --fixfrq 4000 --fast`
ran for 11 min 42 sec and cuda crashed with this error message:

> cuda_driver : DEBUG    finished processing CUDA_GENERATE_PULSE command, responding
> cuda_driver : DEBUG    responded to CUDA_GENERATE_PULSE,  waiting for next command
> cuda_driver : DEBUG    received CUDA_PROCESS command
> cudamsg_handler: DEBUG    enter cuda_process_handler (swing 0)
> cuda_gpu    : DEBUG    nSamples_rx: bb=10764, if=1076500, rf=32295030
> Traceback (most recent call last):
>   File "./cuda_driver.py", line 1106, in <module>
>     main()
>   File "./cuda_driver.py", line 1097, in main
>     handler.process()
>   File "./cuda_driver.py", line 384, in process
>     self.gpu.rx_init(swing, cmd.payload['nSamples'])
>   File "./cuda_driver.py", line 673, in rx_init
>     self.rx_rf_samples = cuda.pagelocked_empty((self.nAntennas,  self.rx_rf_nSamples*2), np.int16, mem_flags=cuda.host_alloc_flags.DEVICEMAP)
> pycuda._driver.MemoryError: cuMemHostAlloc failed: out of memory
